### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ramarty** [ramarty/Unique-Location-Extractor#1]
I've just started to try to get things working as somewhat user-friendly functions, so I'm looking for feedback on the following: if you were a user that wanted to use this package-in-development, (1) they things work, (2) do the two main functions make sense, (3) what is super confusing?

- [ ] Does the example work? The example uses the minimum set of inputs required - do these inputs make sense?

- [ ] Does the description on the readme generally make sense? This was all somewhat quickly written so my guess is parts are confusing / not written well -- so what areas stand out in not making sense?

- [ ] Do the outputs of each function make sense? I need to clean and improve the output of locate_event, but the output of augment_gazetteer should make more sense?

- [ ] For the augment_gazetteer and locate_event functions, do the input parameters make sense? I need to give more thought to naming parameters, providing better descriptions, justifying purpose, etc -- but good to know what is super confusing right now.
- [ ] For the augment_gazetteer and locate_event functions, does the purpose of each make sense?

I wouldn't go through all the code, but one that's probably reasonable to go through for the checklist is:
https://github.com/ramarty/Unique-Location-Extractor/blob/master/R/augment_gazetteer.R

Here's the DIME Analytics checklist -- not everything will be relevant here I think:

Code
- [ ] Includes a master script
- [ ] Master script clearly indicates which line needs to be changed to run in a different computer
- [ ] The master script runs from start to end if the reviewer changes only directory path(s) in one
location of the master script
- [ ] The master script installs any commands required (e.g. from SSC in Stata, CRAN in R, etc.)
- [ ] In Stata, the master do file sets critical configurations such as version, matsize, and varabbrev
(either sets directly or through a wrapper command such as ieboilstart from ietoolkit
- [ ] In R, all necessary packages to run the code are loaded in the master script

Data
- [ ] Is fully de-identified
- [ ] All data necessary to run the code to be reviewed is included

Outputs
- [ ] All outputs created by the code to be review are included
- [ ] It is easy to identify which code creates which output

Recommended Practices
- [ ] Scripts for data cleaning, variable creation, and analysis are separate; and analysis scripts do not
- [ ] include any data processing, unless necessary for the creation of a table or graphic
- [ ] All scripts are well-commented and formatted, such that one can easily identify functional chunks of code and evaluate whether they correctly implement the econometric or statistical process described
- [ ] Variable construction scripts include detailed comments about each variable created
- [ ] Analysis scripts do not depend on having the results of other scripts in memory, except for the Master script
- [ ] Tables are output as .csv or .tex files or other raw text files when possible

**Comment by manuelmrm** [comment]
Followed your steps, and I attach a word doc as well :)

[code review _MR.docx](https://github.com/ramarty/Unique-Location-Extractor/files/4664439/code.review._MR.docx)
